require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - bin/*
    - db/schema.rb
  NewCops: enable

Style/Documentation:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

